[build]
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "gatsby develop"
  targetPort = 8000

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
